export enum AmplitudeEvent {
    NEW_SESSION = 'NEW_SESSION',
    SEARCH = 'SEARCH',
    SEARCH_SUCCESS = 'SEARCH_SUCCESS',
    SEARCH_FAIL = 'SEARCH_FAIL',
    SEARCH_MORE = 'SEARCH_MORE',
    VIEW_PROFILE = 'VIEW_PROFILE',
}
